# Generated by Django 3.2.13 on 2022-07-06 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dreidlogin', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='human',
            name='birth_year',
            field=models.CharField(default='99', max_length=200),
            preserve_default=False,
        ),
    ]
