# Generated by Django 3.2.13 on 2022-07-08 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dreidlogin', '0002_human_birth_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='human',
            name='birth_year',
            field=models.IntegerField(),
        ),
    ]
