# Generated by Django 3.2.13 on 2022-07-08 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dreidlogin', '0003_alter_human_birth_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='human',
            name='height',
            field=models.IntegerField(),
        ),
    ]
